sudo: required
services: 
  - docker

before_install:
  - docker build -t mjondocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mjondocker/react-test npm test

after_success:
  - docker build -t mjondocker/multi-client ./client
  - docker build -t mjondocker/multi-nginx ./nginx
  - docker build -t mjondocker/multi-server ./server
  - docker build -t mjondocker/multi-worker ./worker